const SCREENS = {
  SPLASH: 'SPLASH_SCREEN',
  APP: {
    _: 'APP_ROOT',
    CONFIRMATION: 'CONFIRMATION_SCREEN',
    HOME: { _: 'HOME_ROOT', CART: 'CART_SCREEN', HOME: 'HOME_SCREEN' },
    PRODUCT: 'PRODUCT_SCREEN',
  },
};

export default SCREENS;
